# Generated by Django 4.2 on 2024-08-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serivces',
            new_name='Services',
        ),
        migrations.DeleteModel(
            name='sp_Serivces',
        ),
    ]
