# Generated by Django 4.2 on 2024-08-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_rename_serivces_services_delete_sp_serivces'),
    ]

    operations = [
        migrations.CreateModel(
            name='sp_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(default='test')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
