# Generated by Django 4.2 on 2024-08-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_sp_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sp_Services',
        ),
        migrations.AddField(
            model_name='services',
            name='sp',
            field=models.BooleanField(default=False),
        ),
    ]
