# Generated by Django 4.2 on 2024-08-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_delete_sp_services_services_sp'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='services',
            name='sp',
        ),
    ]
