# Generated by Django 4.2 on 2024-08-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='content',
            field=models.TextField(default='test'),
        ),
    ]
